### PR TITLE
update to 0.6.3

### PR DESCRIPTION
**Pull request by gotcha**

### CODE REVIEW

**Comment by AVVS** [comment]
we should also update alpine to 3.6 and glibc to 2.25

**Comment by gotcha** [comment]
updated

**Comment by AVVS** [comment]
Thanks!

**Comment by gotcha** [comment]
FYI, when Travis attempted to push new images to docker hub, it got
```denied: requested access to the resource is denied```

See https://travis-ci.org/makeomatic/nomad/builds/286565473?utm_source=github_status&utm_medium=notification

**Pull request merged**
